language: php
php:
- 5.3
- 5.4
- 5.5
- 5.6
- hhvm
install: composer install
script: make
notifications:
  email: false
  slack:
    rooms:
      secure: "zldnxLhyDn2l7ru814x9ayYGKlQOM0g3DUI06cujjyyU94En0I0KLL1NsCE3M+wjqco18vC8MOruQMym6Qfo7fRluhzC8ZQRXzZawjy2CJV2GL51Bp84aLAXnBH+I0hBuMxB1me2hkuVRPEzB2uuFboyxj9Vm4rf887IS8tilPy43mVRh9gROdQPh0Hoe8gVj9Hf3QzKCECg/0fXWMXuUyOPHFgEW6RN2bMEym9Qr86eq0dqJP6FVTYkQxPsjun8aSJQ3Cjpq2TY9LY33VFp6FAXOv2DnVurDYyTxny5UhQTaDmCrh4+cdhlJ4uO3bwFv8nlSfIjcGrpNj+IMYz5fdXIsPulFLcMrLR0RzrVNNyK/OcwERoZOcJpYYR+PeG31ZyjPAfT1Ltfw/yixj353n4aWwmUk1XPkh8OCUqusNlLYiX7H48V6ODCA0qO3PYJ3vSIym+CwAGcIj1WEM5n10MXgDV2Ud9WI2EdyKu2eaD3vfLK05E26c3FZEivEaCt60e3BzGUSdjy2+HS0lrJ+da46dDa/fzf6q3CxHz0hyVSKtl4rLEynRVZMlAFYXMkn1Eo45jfxPVfDXww5nq95rMRO0fBYljgE/S9WvEEKDdwrQLe1OFdwq5VDrOtQi6qrnAPtaWhHX8NQ/GCXE0WizoVU04C6xZSUoycRV+/2ic="
    on_pull_requests: false
