language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install: composer install

script: make

notifications:
  email: false
  slack:
    secure: 'iDxBk8No5VjJI4onG2uPYaNA2w1qOe0yxqgBG1SgKUuct22CQnBQNC1dZIA3BpO2ZDyYJA0A3XK2HzlE/zh9hedyHi+PUtv1iN1TZGGccaAxUmgAgsqn9UHXgHZI4j3S4Ss8N2Wo3UwGGGdnvhqYvXGYFfDbUK2+/G85yT6CntV9aqTGgg/rXrvemCx7oMD5qITOnUF+5VBYoy9yDOoHGrcF4qxoBhEVb7rDpCDHd0OoBkE6c9xichIj0fCLBybg1IaBk+498XPC2O18gkN3A9g107RvUHBgJ7h+rWVL8VDiiLCBfKbtpslhiZzvBAyu9lkVY25iA0ZNq8pkHMB3u4NcLQYZU4NkZd8JoJHntaWn7lYSHFXcqh379xZLmVO25j0IAb9yW+EhNHcaQGEARV8isOXe7Npa5Ws6gZEu5Tg00o6hwki5k16GQ0Lx8Sa5oZ5etlo+6S3UYHFe/k+vdETbdUx1HnI8Q+3BXSk7kF2z424bmW0kLQDdHLjKpDt9mB4y1OUzOHbo8Vm77jgR0LVJG/A4lJ9xVNeBHW56JikZVWrlUclUjpTQwOXYn3e1GpqZeuxw58d0yUHjS0pzUUy6d0oE3nkECLoelC20WhbQoLpfPRJCP/XbUxnnQT7HHFc0/zqk/zlIpQ3TQVYPrghxJ5KkuSz6YpOQzm1Lbfk='
    on_pull_requests: false
