language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install: composer install

script: vendor/bin/phpcs --standard=PSR2 src && vendor/bin/phpcs --standard=PSR2 --error-severity=1 --warning-severity=6 tests && vendor/bin/phpunit